### ISSUE TITLE
Multiple issues with the Tickable setting for variables

### ISSUE THREAD

**Issue by pedrotski** [wisp-gg/issue-tracker#13]
### Describe the bug

If you have Tickable set and the variable rule is boolean, you cannot set it to 0 by default and save it. It will revert to 1. 

Furthermore, if a toggle is set to 1 by default and you deploy a server, on the front end it will be displayed as 0 or off. 

Another issue that confuses customers is it always says ENABLED on the front end even when the toggle is off, so they assume it's actually enabled.

### Expected Behavior

Make the above functional.

### Actual Behavior

NA

### Steps to Reproduce

NA

### Browser Details

NA

### Operating System

NA

**Comment by Lunaversitay** [comment]
This bug is due to backend validation forcing tickables to be a boolean, but it only sticks the value to `1`. This will be fixed soon!

**Comment by joti-prime** [comment]
Tickable variables will be useful if when ticket adds some code and when not removes that code from the startup like actually doesn’t work
