### ISSUE TITLE
Missing location descriptions for geo routing

### ISSUE THREAD

**Issue by JouanDeag** [wisp-gg/issue-tracker#32]
### Describe the bug

Location descriptions seem to be missing after the infrastructure change and now returns "Unknown".

In addition, this tooltip also hovers in the middle of the screen on a fully populated page.

![image](https://github.com/user-attachments/assets/fd33d89f-dd7c-485b-bf28-04fea2024a43)

### Expected Behavior

Show the actual location.

### Actual Behavior

See above.

### Steps to Reproduce

1. Visit any page
2. Hover the location / version at the bottom
3. See issue

### Browser Details

N/A

### Operating System

N/A

**Comment by mason-rogers** [comment]
fixed in next update
