### ISSUE TITLE
Server Info

### ISSUE THREAD

**Issue by andre2843** [wisp-gg/issue-tracker#37]
### Describe the bug

The Server Info feature doesn't work in most games. Especially in Counter-Strike 1.6 and Counter-Strike: Source.

### Expected Behavior

That shows Hostname, Version, Map and Players correctly.

### Actual Behavior

The information remains as Unknown.

### Steps to Reproduce

System > Server Details > Server Info.

### Browser Details

Chrome

### Operating System

Debian 12

### Optional additional information

```bash
https://i.imgur.com/gqWU7hJ.png
```

**Comment by pedrotski** [comment]
This is a configuration issue on your end for the most part - https://gamepanel.notion.site/Egg-Configuration-c2fc1c743ba541bb87f33f84226df4ee#d10fe2f96b994886b626fa2b9cdfdcde

The Gamedig query is outdated but it 100% works with those older games.

**Comment by Lunaversitay** [comment]
Since this is a misconfigured egg I'll be closing this.
