### ISSUE TITLE
Gamedig is outdated

### ISSUE THREAD

**Issue by pedrotski** [wisp-gg/issue-tracker#4]
### Describe the bug

Gamedig is 4 years old

### Expected Behavior

Gamedig should be the latest version

### Actual Behavior

Gamedig should be the latest version

### Steps to Reproduce

1. Set the query for any new game
2. Watch it not work

### Browser Details

Internet Explorer 4.1

### Operating System

Windows 95

**Comment by mason-rogers** [comment]
fixed in daemon v2.2.3
