### ISSUE TITLE
Add Latin America POP

### ISSUE THREAD

**Issue by 0xCiBeR** [wisp-gg/issue-tracker#42]
### Describe the feature and why you would like to see it.

Please add a latin america POP for improved latency

### Describe the solution you'd like.

New latin america POP, brazil has good connections to most latin america countries but also could be Argentina/Chile

**Comment by Lunaversitay** [comment]
I believe we'd like to keep this repo mostly to technical issues. For infrastructure related queries we have internal notes on the matter. Ideally in the future we want a PoP in every continent. But at the moment we are still in the process of ensuring the infrastructure is upgraded with no issues.
