### ISSUE TITLE
Subdomains Cloudflare

### ISSUE THREAD

**Issue by joti-prime** [wisp-gg/issue-tracker#46]
### Describe the feature and why you would like to see it.

Be able to control subdomains through own Cloudflare account. (I have some domains in Cloudflare and with the free tier is impossible to change the nameservers)

### Describe the solution you'd like.

Implement Cloudflare for subdomains.

**Comment by Lunaversitay** [comment]
I'm unfamiliar with how CloudFlare works with domains but if you paid for a domain it should allow you to change the name servers. You may likely be missing something. 
If this is intended on their end we likely wouldn't be-able to justify development time into creating a whole new system just to interact with the CloudFlare API. No other domain registrar has this issue and this is the first time we've heard of it so this will likely not be implemented right now.
