### ISSUE TITLE
Uploading files

### ISSUE THREAD

**Issue by joti-prime** [wisp-gg/issue-tracker#48]
### Describe the bug

1 allow to upload more than 1GB
2 provide a better feedback: some times the progress bar gets stuck and the user don’t know if the files was correctly upload or what happened.

### Expected Behavior

Feedback 

### Actual Behavior

No feedback 

### Steps to Reproduce

Upload a file

### Browser Details

Chrome

### Operating System

Windows 10

**Comment by Lunaversitay** [comment]
For the web file manager we will likely not be implementing an increased limit over 1GB, the daemon will likely struggle which is why we recommend using SFTP instead for larger file uploads. The file manager is intended for quick edits and smaller uploads.
