### ISSUE TITLE
Add webhook alerts

### ISSUE THREAD

**Issue by joti-prime** [wisp-gg/issue-tracker#51]
### Describe the feature and why you would like to see it.

Add the option to send alerts of the resources through webhooks for example if a server is using too much network or ram or cpu or node in general… 

### Describe the solution you'd like.

Implement it

**Comment by anthonyphysgun** [comment]
I think this is less a WISP thing, and more something that your own external monitoring should handle. Something like Hetrix tools, or using the daemon prometheus exporter endpoint.
