### ISSUE TITLE
Node on VPS using 100% of the CPU

### ISSUE THREAD

**Issue by joti-prime** [wisp-gg/issue-tracker#53]
### Describe the bug

I tried to use a node in AWS and Azure VMs, and when the VM’s CPU load exceeds 95%, the node gets disconnected from the panel, so it says offline, when the load goes down it says online again. Additionally, each server displays the message: ‘There was an exception while attempting to communicate with the daemon.

### Expected Behavior

To be online always

### Actual Behavior

Goes offline when cpu load is high

### Steps to Reproduce

Use a vps install the wisp daemon, run servers to get 95+% of the cpu and you will see that node goes offline so you can’t perform any action from the panel but servers still online.

### Browser Details

Chrome

### Operating System

Win11

**Comment by Lunaversitay** [comment]
Unfortunately if the daemon does not have enough resources to run then there is not much else that can be done.
The daemon is extremely light weight, if you are having CPU issues I would recommend upgrading your hardware instead.
