### ISSUE TITLE
WISP "Manage Application API" keeps reverting rights back to None.

### ISSUE THREAD

**Issue by isag33k** [wisp-gg/issue-tracker#55]
### Describe the bug

When adding a Application API in Administration Panel and selecting Read & Write for all categories, the settings will not maintain after hitting Save. If you go back into the generated API key (Manage) all the rights are back to "None". Even deleting and recreating a new API Key (with a different name) displays the same behavior.

### Expected Behavior

Once the API Key is created and permissions have been set, hitting Save should maintain the rights. 

### Actual Behavior

This is not the case and verified if you leave the Manage API screen and come back in, you will see all Permissions set back to None.

### Steps to Reproduce

1. Go to Administration
2. Click on Application API
3. Click Create
4. Set  all permissions to Read & Write
5. Name the API
6. Hit Save

### Browser Details

Newest Chome as well as Edge browser

### Operating System

Windows 11 Pro

**Comment by Lunaversitay** [comment]
To clarify this does still save however you need to refresh cause the API key does not live update.
