### ISSUE TITLE
Add NeoForge - Advanced 

### ISSUE THREAD

**Issue by SNokerYT** [wisp-gg/issue-tracker#57]
### Describe the feature and why you would like to see it.

Version - NeoForge 

### Describe the solution you'd like.

Version - NeoForge

**Comment by pedrotski** [comment]
Issue already exists - https://github.com/wisp-gg/issue-tracker/issues/43

**Comment by anthonyphysgun** [comment]
Duplicate of https://github.com/wisp-gg/issue-tracker/issues/43
